/**
 * Citation-tag correctness gate harness (citation-recon R3, #20, AC4)
 *
 * Pure functions over a gold fixture, mirroring the decay-weight gate harness
 * (decay-gate.ts). Runs the REAL evidence resolver (resolveEvidenceEdges) + the REAL
 * tag derivation (citationTag) — never a re-implementation — so the gate measures
 * exactly what production tags, and any drift fails CI. The commit-existence oracle
 * is injected from the fixture's `knownCommits` set (the same seam the index wires a
 * git-backed checker into), so the gate covers the R3 fold's real-vs-syntactic band
 * deterministically, with no git IO.
 */
import { KnowledgeGraph } from '../../src/graph/graph.js';
import { RelationshipType } from '../../src/graph/types.js';
import type { Relationship } from '../../src/graph/types.js';
import type { EvidenceSignal } from '../../src/analyzers/markdown.js';
import { resolveEvidenceEdges, citationTag } from '../../src/analyzers/evidence-edges.js';

/** A citation's expected verdict: a real tag, or `no-edge` when precision must drop it. */
export type ExpectedTag = 'resolved' | 'inferred' | 'no-edge';

/** One gold citation case: a raw evidence signal + the tag the resolver MUST produce. */
export interface CitationCase {
  name: string;
  kind: RelationshipType; // EVIDENCED_BY | DOCUMENTED_BY — which emitted edge to read
  signal: EvidenceSignal;
  expect: ExpectedTag;
}

export interface GateInput {
  graph: KnowledgeGraph;
  cases: CitationCase[];
  /** Shas KNOWN to exist in history — the injected commitExists oracle (no git IO). */
  knownCommits: Set<string>;
}

export interface CaseResult {
  name: string;
  kind: string;
  expected: ExpectedTag;
  actual: ExpectedTag;
  pass: boolean;
}

export interface GateResult {
  cases: CaseResult[];
  /** Two resolver passes over the same fixture are byte-identical. */
  deterministic: boolean;
  verdict: 'pass' | 'fail';
}

/** The effective tag of a case's emitted edge, or `no-edge` when the resolver dropped it. */
function tagForCase(edges: Relationship[], c: CitationCase): ExpectedTag {
  // All edges a single signal emits for one kind share the same commit watermark, so
  // they share one tag — reading the first is sufficient and deterministic.
  const edge = edges.find((e) => e.sourceId === c.signal.sourceId && e.type === c.kind);
  return edge ? citationTag(edge) : 'no-edge';
}

/**
 * Run the gate: resolve all gold signals once (production path) with the injected
 * commit oracle, tag each case, and pass only when EVERY case matches AND the resolver
 * is deterministic (a second identical pass).
 */
export function runGate(input: GateInput): GateResult {
  const commitExists = (sha: string): boolean => input.knownCommits.has(sha);
  const signals: EvidenceSignal[] = input.cases.map((c) => c.signal);

  const first = resolveEvidenceEdges(input.graph, signals, commitExists);
  const second = resolveEvidenceEdges(input.graph, signals, commitExists);
  const deterministic = JSON.stringify(first) === JSON.stringify(second);

  const cases: CaseResult[] = input.cases.map((c) => {
    const actual = tagForCase(first, c);
    return { name: c.name, kind: c.kind, expected: c.expect, actual, pass: actual === c.expect };
  });

  const verdict: GateResult['verdict'] = cases.every((c) => c.pass) && deterministic ? 'pass' : 'fail';
  return { cases, deterministic, verdict };
}

/** The durable markdown record (snapshotted to docs/eval/0006), mirroring the decay gate. */
export function renderGateReport(r: GateResult): string {
  const passing = r.cases.filter((c) => c.pass).length;
  const lines: string[] = [
    '# Citation-Tag Correctness Gate — recon ADR 0006 (citation-recon R3 / #20)',
    '',
    '> Durable record of the MANDATORY gate (AC4). Generated by the citation-tag harness',
    '> (`test/unit/citation-tag-gate.test.ts`) over the gold fixture and verified on every',
    '> run; regenerate with `vitest -u`. It runs the REAL evidence resolver + `citationTag`',
    '> over known citations and proves each is tagged correctly + deterministically — so',
    "> recon_explain's resolved/inferred surfacing and its verified-only view can be trusted.",
    '',
    `## Verdict: ${r.verdict.toUpperCase()}${r.verdict === 'pass'
      ? ' → the resolver tags every gold citation correctly'
      : ' → a citation was mis-tagged'}`,
    '',
    `- Deterministic (two resolver passes byte-identical): **${r.deterministic ? 'yes' : 'no'}**`,
    `- Cases passing: **${passing} / ${r.cases.length}**`,
    '',
    '## Gold fixture (measured, not guessed)',
    '',
    '| citation | edge | expected | actual | pass |',
    '|---|---|:--:|:--:|:--:|',
    ...r.cases.map((c) => `| ${c.name} | ${c.kind} | ${c.expected} | ${c.actual} | ${c.pass ? 'yes' : 'no'} |`),
    '',
    '## The bands (AC1–AC4)',
    '',
    '- **resolved** — fact-verified: the target node provably exists AND, for an',
    '  EVIDENCED_BY commit watermark, the sha is present in git history (R3 fold). The',
    '  only band the `verified: true` view keeps.',
    '- **inferred** — the link is emitted (target exists) but its commit watermark is',
    '  unverified: well-formed but absent from history, or malformed. KEPT + flagged so',
    '  the citation stays visible, never silently dropped; excluded by `verified: true`.',
    '- **no edge** — precision-first: an evidence.symbols entry that does not resolve to a',
    '  real node yields NO DOCUMENTED_BY edge at all — the resolver never mints a false `resolved`.',
    '',
  ];
  return lines.join('\n');
}
